
import React, { useState } from 'react';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { FileText, Download, Check, ArrowLeft, Wallet } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Transaction, TaxSummary } from '@/types/transaction';

interface PDFExporterProps {
  taxSummary: TaxSummary;
  transactions: Transaction[];
  walletAddresses: string[];
}

export const PDFExporter: React.FC<PDFExporterProps> = ({ taxSummary, transactions, walletAddresses }) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [isComplete, setIsComplete] = useState(false);
  const { toast } = useToast();

  const generatePDF = async () => {
    setIsGenerating(true);
    
    // Simulate PDF generation
    setTimeout(() => {
      setIsGenerating(false);
      setIsComplete(true);
      
      // Create and trigger download of a mock PDF file
      const pdfContent = generatePDFContent();
      const blob = new Blob([pdfContent], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Tax3_Unified_Report_2024_${walletAddresses.length}_wallets.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast({
        title: "Unified Tax Report Generated",
        description: "Your comprehensive PDF report has been downloaded successfully.",
      });
    }, 3000);
  };

  const generatePDFContent = () => {
    const walletSummaries = walletAddresses.map((address, index) => {
      const shortAddress = address.slice(0, 8) + '...' + address.slice(-4);
      const walletTxs = transactions.filter(tx => tx.walletAddress === shortAddress);
      return `
=== WALLET ${index + 1} SUMMARY ===
Address: ${address}
Total Transactions: ${walletTxs.length}
Transaction Types:
- Transfers: ${walletTxs.filter(tx => tx.type === 'transfer').length}
- Trades: ${walletTxs.filter(tx => tx.type === 'trade').length}
- Swaps: ${walletTxs.filter(tx => tx.type === 'swap').length}
- Staking: ${walletTxs.filter(tx => tx.type === 'staking').length}
- DeFi: ${walletTxs.filter(tx => tx.type === 'defi').length}
`;
    }).join('\n');

    return `
TAX3 - UNIFIED CRYPTO TAX REPORT 2024
Generated on: ${new Date().toLocaleDateString()}
Report Type: Multi-Wallet Unified Analysis
Total Wallets: ${walletAddresses.length}

=== EXECUTIVE SUMMARY ===
Total Capital Gains: $${taxSummary.totalGains.toFixed(2)}
Total Capital Losses: $${taxSummary.totalLosses.toFixed(2)}
Net Capital Result: $${taxSummary.netGains.toFixed(2)}

Short-term Gains: $${taxSummary.shortTermGains.toFixed(2)}
Long-term Gains: $${taxSummary.longTermGains.toFixed(2)}
Staking Income: $${taxSummary.stakingIncome.toFixed(2)}

Total Transactions Analyzed: ${taxSummary.totalTransactions}
Analysis Method: FIFO (First In, First Out)
Compliance: US Tax Code (IRS Publication 544)

${walletSummaries}

=== DETAILED TRANSACTION LOG ===
${transactions.slice(0, 100).map(tx => `
Date: ${tx.timestamp.toLocaleDateString()}
Wallet: ${tx.walletAddress}
Type: ${tx.type.toUpperCase()}
Direction: ${tx.direction.toUpperCase()}
Amount: ${tx.amount} ${tx.token}
Price: $${(tx.price || 0).toFixed(2)}
Value: $${((tx.amount * (tx.price || 0))).toFixed(2)}
Classification: ${tx.classification.toUpperCase()}
Signature: ${tx.signature}
`).join('\n')}

${transactions.length > 100 ? `\n... and ${transactions.length - 100} more transactions` : ''}

=== TAX FORMS GUIDANCE ===
Form 8949: Report all capital gains and losses from crypto transactions
Schedule D: Summarize total capital gains/losses
Schedule 1: Report any staking income as "Other Income"

=== METHODOLOGY ===
- Cost Basis: FIFO (First In, First Out) method applied
- Price Data: Historical market prices at transaction time
- Cross-Wallet Optimization: Transactions analyzed across all wallets for optimal tax treatment
- Duplicate Detection: Cross-wallet duplicate transactions identified and removed

=== DISCLAIMER ===
This report is generated for informational purposes only. 
Please consult with a qualified tax professional for tax advice.
The calculations are based on FIFO cost basis method and US tax rules.
Tax3 does not provide tax, legal, or accounting advice.

Generated by Tax3 - Professional Crypto Tax Reporting
Version 1.0 | Report ID: ${Date.now()}
`;
  };

  if (isComplete) {
    return (
      <div className="min-h-screen bg-black">
        <div className="container mx-auto px-4 sm:px-6 py-12">
          <Card className="max-w-4xl mx-auto bg-card border-border">
            <div className="p-6 sm:p-8 text-center">
              <div className="w-16 h-16 bg-emerald-500/20 rounded-full flex items-center justify-center mx-auto mb-6">
                <Check className="w-8 h-8 text-emerald-400" />
              </div>
              <h2 className="text-2xl sm:text-3xl font-sans font-bold text-white mb-4">
                Unified Report Generated Successfully!
              </h2>
              <p className="text-muted-foreground mb-8">
                Your comprehensive Tax3 unified report covering {walletAddresses.length} wallets has been generated and downloaded.
              </p>
              
              {/* Report Summary */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
                <div className="p-4 bg-primary/10 border border-primary/20 rounded-lg">
                  <div className="text-2xl font-bold text-primary mb-2">{walletAddresses.length}</div>
                  <div className="text-sm text-muted-foreground">Wallets Analyzed</div>
                </div>
                <div className="p-4 bg-emerald-500/10 border border-emerald-500/20 rounded-lg">
                  <div className="text-2xl font-bold text-emerald-400 mb-2">
                    {taxSummary.totalTransactions.toLocaleString()}
                  </div>
                  <div className="text-sm text-muted-foreground">Total Transactions</div>
                </div>
                <div className="p-4 bg-purple-500/10 border border-purple-500/20 rounded-lg">
                  <div className="text-2xl font-bold text-purple-400 mb-2">
                    ${Math.abs(taxSummary.netGains).toLocaleString(undefined, { minimumFractionDigits: 0 })}
                  </div>
                  <div className="text-sm text-muted-foreground">Net Capital Result</div>
                </div>
              </div>

              <div className="space-y-6 mb-8">
                <div className="p-6 bg-primary/10 border border-primary/20 rounded-lg text-left">
                  <h3 className="text-primary font-medium mb-4 flex items-center">
                    <FileText className="w-5 h-5 mr-2" />
                    What's Included in Your Unified Report:
                  </h3>
                  <ul className="text-muted-foreground text-sm space-y-2">
                    <li>• Cross-wallet transaction analysis with duplicate detection</li>
                    <li>• Optimized cost basis calculations using FIFO method</li>
                    <li>• Individual wallet breakdowns and combined summary</li>
                    <li>• Short-term vs long-term capital gains classification</li>
                    <li>• Comprehensive staking income calculations</li>
                    <li>• IRS-compliant formatting with Form 8949 guidance</li>
                  </ul>
                </div>
                
                <div className="p-6 bg-yellow-500/10 border border-yellow-500/20 rounded-lg text-left">
                  <h3 className="text-yellow-400 font-medium mb-4">Next Steps for Tax Filing:</h3>
                  <ul className="text-muted-foreground text-sm space-y-2">
                    <li>• Review the unified report with your tax professional</li>
                    <li>• Use Form 8949 data to complete your tax return</li>
                    <li>• Keep all wallet reports for your tax records</li>
                    <li>• Consider quarterly estimated payments for next year</li>
                    <li>• Set up record-keeping for ongoing transactions</li>
                  </ul>
                </div>

                {/* Wallet Summary */}
                <div className="p-6 bg-muted/10 border border-border rounded-lg text-left">
                  <h3 className="text-white font-medium mb-4 flex items-center">
                    <Wallet className="w-5 h-5 mr-2" />
                    Wallets Included in This Report:
                  </h3>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    {walletAddresses.map((address, index) => (
                      <div key={address} className="p-3 bg-card border border-border rounded-lg">
                        <div className="flex items-center space-x-2">
                          <span className="text-xs text-muted-foreground">Wallet {index + 1}:</span>
                          <span className="font-mono text-sm text-white">
                            {address.slice(0, 8)}...{address.slice(-4)}
                          </span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>

              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Button 
                  onClick={generatePDF}
                  className="bg-primary hover:bg-primary/90 text-primary-foreground"
                >
                  <Download className="w-4 h-4 mr-2" />
                  Download Again
                </Button>
                <Button 
                  onClick={() => window.location.reload()}
                  variant="outline"
                  className="border-border text-foreground hover:bg-muted"
                >
                  <ArrowLeft className="w-4 h-4 mr-2" />
                  Generate New Report
                </Button>
              </div>
            </div>
          </Card>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-black">
      <div className="container mx-auto px-4 sm:px-6 py-12">
        <Card className="max-w-4xl mx-auto bg-card border-border">
          <div className="p-6 sm:p-8">
            <div className="text-center mb-8">
              <div className="w-16 h-16 bg-primary/20 rounded-2xl flex items-center justify-center mx-auto mb-4">
                <FileText className="w-8 h-8 text-primary" />
              </div>
              <h2 className="text-2xl sm:text-3xl font-sans font-bold text-white mb-2">
                Generate Unified PDF Tax Report
              </h2>
              <p className="text-muted-foreground">
                Create your professional unified tax report covering {walletAddresses.length} wallets, ready for IRS filing
              </p>
            </div>

            {/* Report Preview */}
            <div className="bg-muted/20 rounded-lg p-6 mb-8 border border-border">
              <h3 className="text-white font-semibold mb-4">Unified Report Contents:</h3>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-3">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Total Wallets:</span>
                    <span className="text-primary font-mono">{walletAddresses.length}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Total Gains:</span>
                    <span className="text-emerald-400 font-mono">${taxSummary.totalGains.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Total Losses:</span>
                    <span className="text-red-400 font-mono">${taxSummary.totalLosses.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Net Result:</span>
                    <span className={`font-mono ${taxSummary.netGains >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>
                      ${Math.abs(taxSummary.netGains).toFixed(2)}
                    </span>
                  </div>
                </div>
                <div className="space-y-3">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Short-term:</span>
                    <span className="text-orange-400 font-mono">${taxSummary.shortTermGains.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Long-term:</span>
                    <span className="text-purple-400 font-mono">${taxSummary.longTermGains.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Staking Income:</span>
                    <span className="text-yellow-400 font-mono">${taxSummary.stakingIncome.toFixed(2)}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Transactions:</span>
                    <span className="text-blue-400 font-mono">{taxSummary.totalTransactions.toLocaleString()}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Generate Button */}
            <Button
              onClick={generatePDF}
              disabled={isGenerating}
              className="w-full h-14 bg-primary hover:bg-primary/90 text-primary-foreground font-semibold text-lg"
            >
              {isGenerating ? (
                <>
                  <Download className="w-5 h-5 mr-2 animate-pulse" />
                  Generating Unified PDF Report...
                </>
              ) : (
                <>
                  <FileText className="w-5 h-5 mr-2" />
                  Generate & Download Unified PDF Report
                </>
              )}
            </Button>

            <div className="mt-6 p-4 bg-primary/10 border border-primary/20 rounded-lg">
              <p className="text-primary text-sm text-center">
                <strong>Professional Report:</strong> This unified report provides comprehensive analysis across all your wallets with 
                cross-wallet optimization and IRS-compliant formatting. Please consult with a qualified tax professional for advice.
              </p>
            </div>
          </div>
        </Card>
      </div>
    </div>
  );
};
